#
# Defines environment variables.
#
# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

export HOMEBREW_BOTTLE_DOMAIN=https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles
export HOMEBREW_AUTO_UPDATE_SECS="432000"
PROXY_PORT=8123

start_proxy() {
export http_proxy=http://127.0.0.1:$PROXY_PORT
export https_proxy=http://127.0.0.1:$PROXY_PORT
}

stop_proxy() {
unset http_proxy
unset https_proxy
}

# You may need to manually set your language environment
export LANG=zh_CN.UTF-8
export PYTHONIOENCODING=utf-8

if [ -x "$(command -v nvim)" ]; then
    export EDITOR='nvim'
elif [ -x "$(command -v vim)" ]; then
    export EDITOR='vim'
else
    export EDITOR='vi'
fi

[ -f $HOME/.zshenv.local ] && source $HOME/.zshenv.local

export PATH=${PATH}:$HOME/.local/bin
