#!/bin/sh

if [ -e "$HOME"/.vim/autoload/plug.vim ]; then
  vim -E -s +PlugUpgrade +qa
else
  curl -fLo "$HOME"/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

vim -u "$HOME"/.vimrc.bundles +PlugUpdate +PlugClean! +qa

reset -Q

git clone --recursive https://github.com/sorin-ionescu/prezto.git "$HOME"/.zprezto

git clone https://github.com/skywind3000/z.lua.git "$HOME"/.zprezto/contrib/z.lua
